version: '3'
services:
  app:
    container_name: app
    build: ./doc/docker/php
    volumes:
      - ./:/var/www
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./doc/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: hseinoroot
      MYSQL_DATABASE: aita
      MYSQL_USER: aita
      MYSQL_PASSWORD: aitapassword
      TZ: 'Asia/Tokyo'
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./doc/docker/db/data:/var/lib/mysql
      - ./doc/docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./doc/docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  mailhog:
    image: mailhog/mailhog
    ports:
      - target: 8025
        published: ${MAILHOG_PUBLISHED_PORT:-8025}
        protocol: tcp
        mode: host
